<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_XPoG8FcXEfGWIIPqoQXQhw" name="DiagramaSolicitudVacaciones" version="1.1.0" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_XPoG8VcXEfGWIIPqoQXQhw" name="SolicitudVacaciones" version="1.1.0">
      <elements xmi:type="process:Lane" xmi:id="_XPoG8lcXEfGWIIPqoQXQhw" name="Empleado (lane) " actor="_XPoHOFcXEfGWIIPqoQXQhw">
        <elements xmi:type="process:StartEvent" xmi:id="_XPoG81cXEfGWIIPqoQXQhw" name="Ingresar solicitud" outgoing="_XPoHJlcXEfGWIIPqoQXQhw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XPoG9FcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XPoG9VcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XPoG9lcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_XPoG91cXEfGWIIPqoQXQhw" name="Validar solicitud" outgoing="_XPoHKVcXEfGWIIPqoQXQhw" incoming="_XPoHJlcXEfGWIIPqoQXQhw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XPoG-FcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XPoG-VcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XPoG-lcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XPoG-1cXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XPoG_FcXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XPoG_VcXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XPoG_lcXEfGWIIPqoQXQhw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XPoG_1cXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_8HYR0FcXEfGWIIPqoQXQhw" name="Enviar recordatorio después de 5s" outgoing="_HvBYcFcaEfGWIIPqoQXQhw">
            <condition xmi:type="expression:Expression" xmi:id="_owqNYFcaEfGWIIPqoQXQhw" name="00:00:05" content="5000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_XPoHAFcXEfGWIIPqoQXQhw">
            <targetForm xmi:type="expression:Expression" xmi:id="_XPoHAVcXEfGWIIPqoQXQhw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_XPoHAlcXEfGWIIPqoQXQhw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_XPoHA1cXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_XPoHBFcXEfGWIIPqoQXQhw" name="¿Solicitud aprobada?" outgoing="_XPoHLFcXEfGWIIPqoQXQhw _XPoHL1cXEfGWIIPqoQXQhw" incoming="_XPoHKVcXEfGWIIPqoQXQhw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XPoHBVcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XPoHBlcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XPoHB1cXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_XPoHCFcXEfGWIIPqoQXQhw" name="Notificar aprobación" outgoing="_XPoHMlcXEfGWIIPqoQXQhw" incoming="_XPoHLFcXEfGWIIPqoQXQhw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XPoHCVcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XPoHClcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XPoHC1cXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XPoHDFcXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XPoHDVcXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XPoHDlcXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XPoHD1cXEfGWIIPqoQXQhw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XPoHEFcXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_XPoHEVcXEfGWIIPqoQXQhw" name="Notificar Rechazo" outgoing="_XPoHNVcXEfGWIIPqoQXQhw" incoming="_XPoHL1cXEfGWIIPqoQXQhw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XPoHElcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XPoHE1cXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XPoHFFcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XPoHFVcXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XPoHFlcXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XPoHF1cXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XPoHGFcXEfGWIIPqoQXQhw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XPoHGVcXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_XPoHGlcXEfGWIIPqoQXQhw" name="Fin - Solictud aprobada" incoming="_XPoHMlcXEfGWIIPqoQXQhw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XPoHG1cXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XPoHHFcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XPoHHVcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_XPoHHlcXEfGWIIPqoQXQhw" name="Fin - Solicitud rechazada" incoming="_XPoHNVcXEfGWIIPqoQXQhw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XPoHH1cXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XPoHIFcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XPoHIVcXEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Hu3ncFcaEfGWIIPqoQXQhw" name="Enviar recordatorio de validación" outgoing="_UJ6y4FcaEfGWIIPqoQXQhw" incoming="_HvBYcFcaEfGWIIPqoQXQhw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Hu6qwVcaEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Hu6qwFcaEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Hu6qwlcaEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Hu6qw1caEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Hu6qxFcaEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Hu6qxVcaEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Hu6qx1caEfGWIIPqoQXQhw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Hu6qxlcaEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_UJ49sFcaEfGWIIPqoQXQhw" name="Fin - recordatorio enviado" incoming="_UJ6y4FcaEfGWIIPqoQXQhw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UJ5kwVcaEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UJ5kwFcaEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UJ5kwlcaEfGWIIPqoQXQhw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_XPoHIlcXEfGWIIPqoQXQhw">
        <targetForm xmi:type="expression:Expression" xmi:id="_XPoHI1cXEfGWIIPqoQXQhw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_XPoHJFcXEfGWIIPqoQXQhw">
        <targetForm xmi:type="expression:Expression" xmi:id="_XPoHJVcXEfGWIIPqoQXQhw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XPoHJlcXEfGWIIPqoQXQhw" target="_XPoG91cXEfGWIIPqoQXQhw" source="_XPoG81cXEfGWIIPqoQXQhw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XPoHJ1cXEfGWIIPqoQXQhw"/>
        <condition xmi:type="expression:Expression" xmi:id="_XPoHKFcXEfGWIIPqoQXQhw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XPoHKVcXEfGWIIPqoQXQhw" target="_XPoHBFcXEfGWIIPqoQXQhw" source="_XPoG91cXEfGWIIPqoQXQhw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XPoHKlcXEfGWIIPqoQXQhw"/>
        <condition xmi:type="expression:Expression" xmi:id="_XPoHK1cXEfGWIIPqoQXQhw" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XPoHLFcXEfGWIIPqoQXQhw" name="Sí" target="_XPoHCFcXEfGWIIPqoQXQhw" source="_XPoHBFcXEfGWIIPqoQXQhw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XPoHLVcXEfGWIIPqoQXQhw"/>
        <condition xmi:type="expression:Expression" xmi:id="_XPoHLlcXEfGWIIPqoQXQhw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XPoHL1cXEfGWIIPqoQXQhw" name="No" target="_XPoHEVcXEfGWIIPqoQXQhw" source="_XPoHBFcXEfGWIIPqoQXQhw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XPoHMFcXEfGWIIPqoQXQhw"/>
        <condition xmi:type="expression:Expression" xmi:id="_XPoHMVcXEfGWIIPqoQXQhw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XPoHMlcXEfGWIIPqoQXQhw" target="_XPoHGlcXEfGWIIPqoQXQhw" source="_XPoHCFcXEfGWIIPqoQXQhw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XPoHM1cXEfGWIIPqoQXQhw"/>
        <condition xmi:type="expression:Expression" xmi:id="_XPoHNFcXEfGWIIPqoQXQhw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XPoHNVcXEfGWIIPqoQXQhw" target="_XPoHHlcXEfGWIIPqoQXQhw" source="_XPoHEVcXEfGWIIPqoQXQhw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XPoHNlcXEfGWIIPqoQXQhw"/>
        <condition xmi:type="expression:Expression" xmi:id="_XPoHN1cXEfGWIIPqoQXQhw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HvBYcFcaEfGWIIPqoQXQhw" target="_Hu3ncFcaEfGWIIPqoQXQhw" source="_8HYR0FcXEfGWIIPqoQXQhw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HvB_gFcaEfGWIIPqoQXQhw"/>
        <condition xmi:type="expression:Expression" xmi:id="_HvCmkFcaEfGWIIPqoQXQhw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UJ6y4FcaEfGWIIPqoQXQhw" target="_UJ49sFcaEfGWIIPqoQXQhw" source="_Hu3ncFcaEfGWIIPqoQXQhw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UJ6y4VcaEfGWIIPqoQXQhw"/>
        <condition xmi:type="expression:Expression" xmi:id="_UJ6y4lcaEfGWIIPqoQXQhw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_XPoHOFcXEfGWIIPqoQXQhw" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_XPoHOVcXEfGWIIPqoQXQhw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XPoHOlcXEfGWIIPqoQXQhw">
        <name xmi:type="expression:Expression" xmi:id="_XPoHO1cXEfGWIIPqoQXQhw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XPoHPFcXEfGWIIPqoQXQhw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XPoHPVcXEfGWIIPqoQXQhw">
        <name xmi:type="expression:Expression" xmi:id="_XPoHPlcXEfGWIIPqoQXQhw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XPoHP1cXEfGWIIPqoQXQhw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XPoHQFcXEfGWIIPqoQXQhw">
        <name xmi:type="expression:Expression" xmi:id="_XPoHQVcXEfGWIIPqoQXQhw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XPoHQlcXEfGWIIPqoQXQhw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XPoHQ1cXEfGWIIPqoQXQhw">
        <name xmi:type="expression:Expression" xmi:id="_XPoHRFcXEfGWIIPqoQXQhw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XPoHRVcXEfGWIIPqoQXQhw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XPoHRlcXEfGWIIPqoQXQhw">
        <name xmi:type="expression:Expression" xmi:id="_XPoHR1cXEfGWIIPqoQXQhw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XPoHSFcXEfGWIIPqoQXQhw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_XPoHSVcXEfGWIIPqoQXQhw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_XPoHSlcXEfGWIIPqoQXQhw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_XPoHS1cXEfGWIIPqoQXQhw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_XPoHTFcXEfGWIIPqoQXQhw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_XPoHTVcXEfGWIIPqoQXQhw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_XPoHTlcXEfGWIIPqoQXQhw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_XPoHT1cXEfGWIIPqoQXQhw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_XPoHUFcXEfGWIIPqoQXQhw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_XPoHUVcXEfGWIIPqoQXQhw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_XPoHUlcXEfGWIIPqoQXQhw" type="Process" element="_XPoG8FcXEfGWIIPqoQXQhw" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_XPoHU1cXEfGWIIPqoQXQhw" type="2007" element="_XPoG8VcXEfGWIIPqoQXQhw">
      <children xmi:type="notation:DecorationNode" xmi:id="_XPoHVFcXEfGWIIPqoQXQhw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_XPoHVVcXEfGWIIPqoQXQhw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_XPoHVlcXEfGWIIPqoQXQhw" type="3007" element="_XPoG8lcXEfGWIIPqoQXQhw">
          <children xmi:type="notation:DecorationNode" xmi:id="_XPoHV1cXEfGWIIPqoQXQhw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_XPoHWFcXEfGWIIPqoQXQhw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_XPoHWVcXEfGWIIPqoQXQhw" type="3005" element="_XPoG91cXEfGWIIPqoQXQhw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XPoHWlcXEfGWIIPqoQXQhw" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_8HpXkFcXEfGWIIPqoQXQhw" type="3064" element="_8HYR0FcXEfGWIIPqoQXQhw" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_8Hp-oFcXEfGWIIPqoQXQhw" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_8Hp-oVcXEfGWIIPqoQXQhw" x="3" y="51"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8HpXkVcXEfGWIIPqoQXQhw" x="37" y="42"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XPoHW1cXEfGWIIPqoQXQhw" x="158" y="155"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XPoHXFcXEfGWIIPqoQXQhw" type="3002" element="_XPoG81cXEfGWIIPqoQXQhw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XPoHXVcXEfGWIIPqoQXQhw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XPoHXlcXEfGWIIPqoQXQhw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XPoHX1cXEfGWIIPqoQXQhw" x="86" y="162"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XPoHYFcXEfGWIIPqoQXQhw" type="3008" element="_XPoHBFcXEfGWIIPqoQXQhw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XPoHYVcXEfGWIIPqoQXQhw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XPoHYlcXEfGWIIPqoQXQhw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XPoHY1cXEfGWIIPqoQXQhw" x="374" y="162" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XPoHZFcXEfGWIIPqoQXQhw" type="3027" element="_XPoHCFcXEfGWIIPqoQXQhw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XPoHZVcXEfGWIIPqoQXQhw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XPoHZlcXEfGWIIPqoQXQhw" x="546" y="18" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XPoHZ1cXEfGWIIPqoQXQhw" type="3027" element="_XPoHEVcXEfGWIIPqoQXQhw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XPoHaFcXEfGWIIPqoQXQhw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XPoHaVcXEfGWIIPqoQXQhw" x="546" y="258"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XPoHalcXEfGWIIPqoQXQhw" type="3003" element="_XPoHGlcXEfGWIIPqoQXQhw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XPoHa1cXEfGWIIPqoQXQhw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XPoHbFcXEfGWIIPqoQXQhw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XPoHbVcXEfGWIIPqoQXQhw" x="734" y="33"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XPoHblcXEfGWIIPqoQXQhw" type="3003" element="_XPoHHlcXEfGWIIPqoQXQhw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XPoHb1cXEfGWIIPqoQXQhw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XPoHcFcXEfGWIIPqoQXQhw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XPoHcVcXEfGWIIPqoQXQhw" x="734" y="258"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Hu744FcaEfGWIIPqoQXQhw" type="3027" element="_Hu3ncFcaEfGWIIPqoQXQhw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Hu8f8FcaEfGWIIPqoQXQhw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Hu744VcaEfGWIIPqoQXQhw" x="119" y="337" width="184" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UJ6L0FcaEfGWIIPqoQXQhw" type="3003" element="_UJ49sFcaEfGWIIPqoQXQhw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_UJ6L0lcaEfGWIIPqoQXQhw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_UJ6L01caEfGWIIPqoQXQhw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UJ6L0VcaEfGWIIPqoQXQhw" x="398" y="354"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_XPoHclcXEfGWIIPqoQXQhw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_XPoHc1cXEfGWIIPqoQXQhw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_XPoHdFcXEfGWIIPqoQXQhw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_XPoHdVcXEfGWIIPqoQXQhw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XPoHdlcXEfGWIIPqoQXQhw" x="53" y="10" width="1292" height="489"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_XPoHd1cXEfGWIIPqoQXQhw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_XPoHeFcXEfGWIIPqoQXQhw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_XPoHeVcXEfGWIIPqoQXQhw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_XPoHelcXEfGWIIPqoQXQhw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XPoHe1cXEfGWIIPqoQXQhw" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_XPoHfFcXEfGWIIPqoQXQhw"/>
    <edges xmi:type="notation:Connector" xmi:id="_XPoHfVcXEfGWIIPqoQXQhw" type="4001" element="_XPoHJlcXEfGWIIPqoQXQhw" source="_XPoHXFcXEfGWIIPqoQXQhw" target="_XPoHWVcXEfGWIIPqoQXQhw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XPoHflcXEfGWIIPqoQXQhw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XPoHf1cXEfGWIIPqoQXQhw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XPoHgFcXEfGWIIPqoQXQhw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XPoHgVcXEfGWIIPqoQXQhw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XPoHglcXEfGWIIPqoQXQhw" type="4001" element="_XPoHKVcXEfGWIIPqoQXQhw" source="_XPoHWVcXEfGWIIPqoQXQhw" target="_XPoHYFcXEfGWIIPqoQXQhw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XPoHg1cXEfGWIIPqoQXQhw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XPoHhFcXEfGWIIPqoQXQhw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XPoHhVcXEfGWIIPqoQXQhw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XPoHhlcXEfGWIIPqoQXQhw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XPoHh1cXEfGWIIPqoQXQhw" type="4001" element="_XPoHLFcXEfGWIIPqoQXQhw" source="_XPoHYFcXEfGWIIPqoQXQhw" target="_XPoHZFcXEfGWIIPqoQXQhw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XPoHiFcXEfGWIIPqoQXQhw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XPoHiVcXEfGWIIPqoQXQhw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XPoHilcXEfGWIIPqoQXQhw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XPoHi1cXEfGWIIPqoQXQhw" points="[0, -21, -183, 114]$[0, -136, -183, -1]$[123, -136, -60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XPoHjFcXEfGWIIPqoQXQhw" type="4001" element="_XPoHL1cXEfGWIIPqoQXQhw" source="_XPoHYFcXEfGWIIPqoQXQhw" target="_XPoHZ1cXEfGWIIPqoQXQhw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XPoHjVcXEfGWIIPqoQXQhw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XPoHjlcXEfGWIIPqoQXQhw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XPoHj1cXEfGWIIPqoQXQhw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XPoHkFcXEfGWIIPqoQXQhw" points="[0, 22, -173, -83]$[0, 99, -173, -6]$[123, 99, -50, -6]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XPoHkVcXEfGWIIPqoQXQhw" type="4001" element="_XPoHMlcXEfGWIIPqoQXQhw" source="_XPoHZFcXEfGWIIPqoQXQhw" target="_XPoHalcXEfGWIIPqoQXQhw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XPoHklcXEfGWIIPqoQXQhw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XPoHk1cXEfGWIIPqoQXQhw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XPoHlFcXEfGWIIPqoQXQhw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XPoHlVcXEfGWIIPqoQXQhw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XPoHllcXEfGWIIPqoQXQhw" type="4001" element="_XPoHNVcXEfGWIIPqoQXQhw" source="_XPoHZ1cXEfGWIIPqoQXQhw" target="_XPoHblcXEfGWIIPqoQXQhw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XPoHl1cXEfGWIIPqoQXQhw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XPoHmFcXEfGWIIPqoQXQhw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XPoHmVcXEfGWIIPqoQXQhw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XPoHmlcXEfGWIIPqoQXQhw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HvG4AFcaEfGWIIPqoQXQhw" type="4001" element="_HvBYcFcaEfGWIIPqoQXQhw" source="_8HpXkFcXEfGWIIPqoQXQhw" target="_Hu744FcaEfGWIIPqoQXQhw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HvIGIFcaEfGWIIPqoQXQhw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HvItMFcaEfGWIIPqoQXQhw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HvG4AVcaEfGWIIPqoQXQhw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HvG4AlcaEfGWIIPqoQXQhw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UJ7Z8FcaEfGWIIPqoQXQhw" type="4001" element="_UJ6y4FcaEfGWIIPqoQXQhw" source="_Hu744FcaEfGWIIPqoQXQhw" target="_UJ6L0FcaEfGWIIPqoQXQhw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UJ7Z81caEfGWIIPqoQXQhw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UJ7Z9FcaEfGWIIPqoQXQhw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UJ7Z8VcaEfGWIIPqoQXQhw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UJ7Z8lcaEfGWIIPqoQXQhw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
