<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_0K-kYFZFEfG1Qvt4gaKlAQ" name="DiagramaSolicitudVacaciones" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_0K_LcFZFEfG1Qvt4gaKlAQ" name="SolicitudVacaciones" version="1.0.0">
      <elements xmi:type="process:Lane" xmi:id="_0K_LcVZFEfG1Qvt4gaKlAQ" name="Empleado (lane) " actor="_0K_LilZFEfG1Qvt4gaKlAQ">
        <elements xmi:type="process:StartEvent" xmi:id="_0K_LclZFEfG1Qvt4gaKlAQ" name="Ingresar solicitud" outgoing="_0K_Lh1ZFEfG1Qvt4gaKlAQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0K_Lc1ZFEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0K_LdFZFEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0K_LdVZFEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_0K_LdlZFEfG1Qvt4gaKlAQ" name="Validar solicitud" outgoing="_meVG0lZIEfG1Qvt4gaKlAQ" incoming="_0K_Lh1ZFEfG1Qvt4gaKlAQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0K_Ld1ZFEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0K_LeFZFEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0K_LeVZFEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0K_LelZFEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0K_Le1ZFEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0K_LfFZFEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0K_LfVZFEfG1Qvt4gaKlAQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0K_LflZFEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0K_Lf1ZFEfG1Qvt4gaKlAQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_0K_LgFZFEfG1Qvt4gaKlAQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0K_LgVZFEfG1Qvt4gaKlAQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0K_LglZFEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_w-AxwFZIEfG1Qvt4gaKlAQ" name="¿Solicitud aprobada?" outgoing="_RfjKUFZJEfG1Qvt4gaKlAQ _KWrYQFZLEfG1Qvt4gaKlAQ" incoming="_meVG0lZIEfG1Qvt4gaKlAQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_meT4slZIEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_meT4sVZIEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_meUfwFZIEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_RfhVIFZJEfG1Qvt4gaKlAQ" name="Notificar aprobación" outgoing="_LfpygFZLEfG1Qvt4gaKlAQ" incoming="_RfjKUFZJEfG1Qvt4gaKlAQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RfhVIlZJEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RfhVIVZJEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RfhVI1ZJEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_RfhVJFZJEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_RfhVJVZJEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RfhVJlZJEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_RfhVKFZJEfG1Qvt4gaKlAQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_RfhVJ1ZJEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_KWqKIFZLEfG1Qvt4gaKlAQ" name="Notificar Rechazo" outgoing="_ML9e4FZLEfG1Qvt4gaKlAQ" incoming="_KWrYQFZLEfG1Qvt4gaKlAQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KWqxMVZLEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KWqxMFZLEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KWqxMlZLEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KWqxM1ZLEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KWqxNFZLEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KWqxNVZLEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KWqxN1ZLEfG1Qvt4gaKlAQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KWqxNlZLEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_LfokYFZLEfG1Qvt4gaKlAQ" name="Fin - Solictud aprobada" incoming="_LfpygFZLEfG1Qvt4gaKlAQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LfokYlZLEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LfokYVZLEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_LfokY1ZLEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_ML830FZLEfG1Qvt4gaKlAQ" name="Fin - Solicitud rechazada" incoming="_ML9e4FZLEfG1Qvt4gaKlAQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ML830lZLEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ML830VZLEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ML8301ZLEfG1Qvt4gaKlAQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_0K_Lg1ZFEfG1Qvt4gaKlAQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_0K_LhFZFEfG1Qvt4gaKlAQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_0K_LhVZFEfG1Qvt4gaKlAQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_0K_LhlZFEfG1Qvt4gaKlAQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0K_Lh1ZFEfG1Qvt4gaKlAQ" target="_0K_LdlZFEfG1Qvt4gaKlAQ" source="_0K_LclZFEfG1Qvt4gaKlAQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0K_LiFZFEfG1Qvt4gaKlAQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0K_LiVZFEfG1Qvt4gaKlAQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_meVG0lZIEfG1Qvt4gaKlAQ" target="_w-AxwFZIEfG1Qvt4gaKlAQ" source="_0K_LdlZFEfG1Qvt4gaKlAQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_meVt4FZIEfG1Qvt4gaKlAQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_v9rWIFZIEfG1Qvt4gaKlAQ" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RfjKUFZJEfG1Qvt4gaKlAQ" name="Sí" target="_RfhVIFZJEfG1Qvt4gaKlAQ" source="_w-AxwFZIEfG1Qvt4gaKlAQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RfjKUVZJEfG1Qvt4gaKlAQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_RfjKUlZJEfG1Qvt4gaKlAQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KWrYQFZLEfG1Qvt4gaKlAQ" name="No" target="_KWqKIFZLEfG1Qvt4gaKlAQ" source="_w-AxwFZIEfG1Qvt4gaKlAQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KWrYQVZLEfG1Qvt4gaKlAQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_KWrYQlZLEfG1Qvt4gaKlAQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LfpygFZLEfG1Qvt4gaKlAQ" target="_LfokYFZLEfG1Qvt4gaKlAQ" source="_RfhVIFZJEfG1Qvt4gaKlAQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LfpygVZLEfG1Qvt4gaKlAQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_LfpyglZLEfG1Qvt4gaKlAQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ML9e4FZLEfG1Qvt4gaKlAQ" target="_ML830FZLEfG1Qvt4gaKlAQ" source="_KWqKIFZLEfG1Qvt4gaKlAQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ML9e4VZLEfG1Qvt4gaKlAQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ML9e4lZLEfG1Qvt4gaKlAQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_0K_LilZFEfG1Qvt4gaKlAQ" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_0K_Li1ZFEfG1Qvt4gaKlAQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0K_LjFZFEfG1Qvt4gaKlAQ">
        <name xmi:type="expression:Expression" xmi:id="_0K_LjVZFEfG1Qvt4gaKlAQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0K_LjlZFEfG1Qvt4gaKlAQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0K_Lj1ZFEfG1Qvt4gaKlAQ">
        <name xmi:type="expression:Expression" xmi:id="_0K_LkFZFEfG1Qvt4gaKlAQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0K_LkVZFEfG1Qvt4gaKlAQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0K_LklZFEfG1Qvt4gaKlAQ">
        <name xmi:type="expression:Expression" xmi:id="_0K_Lk1ZFEfG1Qvt4gaKlAQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0K_LlFZFEfG1Qvt4gaKlAQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0K_LlVZFEfG1Qvt4gaKlAQ">
        <name xmi:type="expression:Expression" xmi:id="_0K_LllZFEfG1Qvt4gaKlAQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0K_Ll1ZFEfG1Qvt4gaKlAQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0K_LmFZFEfG1Qvt4gaKlAQ">
        <name xmi:type="expression:Expression" xmi:id="_0K_LmVZFEfG1Qvt4gaKlAQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0K_LmlZFEfG1Qvt4gaKlAQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_0K_Lm1ZFEfG1Qvt4gaKlAQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_0K_LnFZFEfG1Qvt4gaKlAQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_0K_LnVZFEfG1Qvt4gaKlAQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_0K_LnlZFEfG1Qvt4gaKlAQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_0K_Ln1ZFEfG1Qvt4gaKlAQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_0K_LoFZFEfG1Qvt4gaKlAQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_0K_LoVZFEfG1Qvt4gaKlAQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_0K_LolZFEfG1Qvt4gaKlAQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_0K_Lo1ZFEfG1Qvt4gaKlAQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_0K_LpFZFEfG1Qvt4gaKlAQ" type="Process" element="_0K-kYFZFEfG1Qvt4gaKlAQ" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_0K_LpVZFEfG1Qvt4gaKlAQ" type="2007" element="_0K_LcFZFEfG1Qvt4gaKlAQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_0K_LplZFEfG1Qvt4gaKlAQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_0K_Lp1ZFEfG1Qvt4gaKlAQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_0K_LqFZFEfG1Qvt4gaKlAQ" type="3007" element="_0K_LcVZFEfG1Qvt4gaKlAQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_0K_LqVZFEfG1Qvt4gaKlAQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_0K_LqlZFEfG1Qvt4gaKlAQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_0K_Lq1ZFEfG1Qvt4gaKlAQ" type="3005" element="_0K_LdlZFEfG1Qvt4gaKlAQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0K_LrFZFEfG1Qvt4gaKlAQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0K_LrVZFEfG1Qvt4gaKlAQ" x="158" y="155"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0K_LrlZFEfG1Qvt4gaKlAQ" type="3002" element="_0K_LclZFEfG1Qvt4gaKlAQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0K_Lr1ZFEfG1Qvt4gaKlAQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0K_LsFZFEfG1Qvt4gaKlAQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0K_LsVZFEfG1Qvt4gaKlAQ" x="86" y="162"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_w-BY01ZIEfG1Qvt4gaKlAQ" type="3008" element="_w-AxwFZIEfG1Qvt4gaKlAQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_w-B_4FZIEfG1Qvt4gaKlAQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_w-B_4VZIEfG1Qvt4gaKlAQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w-BY1FZIEfG1Qvt4gaKlAQ" x="302" y="162" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RfijQFZJEfG1Qvt4gaKlAQ" type="3027" element="_RfhVIFZJEfG1Qvt4gaKlAQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_RfijQlZJEfG1Qvt4gaKlAQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RfijQVZJEfG1Qvt4gaKlAQ" x="446" y="18" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KWqxOFZLEfG1Qvt4gaKlAQ" type="3027" element="_KWqKIFZLEfG1Qvt4gaKlAQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KWqxOlZLEfG1Qvt4gaKlAQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KWqxOVZLEfG1Qvt4gaKlAQ" x="446" y="258"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_LfpLcFZLEfG1Qvt4gaKlAQ" type="3003" element="_LfokYFZLEfG1Qvt4gaKlAQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_LfpLclZLEfG1Qvt4gaKlAQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_LfpLc1ZLEfG1Qvt4gaKlAQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LfpLcVZLEfG1Qvt4gaKlAQ" x="634" y="33"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ML831FZLEfG1Qvt4gaKlAQ" type="3003" element="_ML830FZLEfG1Qvt4gaKlAQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ML831lZLEfG1Qvt4gaKlAQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ML8311ZLEfG1Qvt4gaKlAQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ML831VZLEfG1Qvt4gaKlAQ" x="634" y="258"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_0K_LslZFEfG1Qvt4gaKlAQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_0K_Ls1ZFEfG1Qvt4gaKlAQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_0K_LtFZFEfG1Qvt4gaKlAQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_0K_LtVZFEfG1Qvt4gaKlAQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0K_LtlZFEfG1Qvt4gaKlAQ" x="28" y="10" width="1292" height="368"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_0K_Lt1ZFEfG1Qvt4gaKlAQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_0K_LuFZFEfG1Qvt4gaKlAQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_0K_LuVZFEfG1Qvt4gaKlAQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_0K_LulZFEfG1Qvt4gaKlAQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0K_Lu1ZFEfG1Qvt4gaKlAQ" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_0K_LvFZFEfG1Qvt4gaKlAQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_0K_LvVZFEfG1Qvt4gaKlAQ" type="4001" element="_0K_Lh1ZFEfG1Qvt4gaKlAQ" source="_0K_LrlZFEfG1Qvt4gaKlAQ" target="_0K_Lq1ZFEfG1Qvt4gaKlAQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0K_LvlZFEfG1Qvt4gaKlAQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0K_Lv1ZFEfG1Qvt4gaKlAQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0K_LwFZFEfG1Qvt4gaKlAQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0K_LwVZFEfG1Qvt4gaKlAQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_meVt4lZIEfG1Qvt4gaKlAQ" type="4001" element="_meVG0lZIEfG1Qvt4gaKlAQ" source="_0K_Lq1ZFEfG1Qvt4gaKlAQ" target="_w-BY01ZIEfG1Qvt4gaKlAQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_meWU8FZIEfG1Qvt4gaKlAQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_meWU8VZIEfG1Qvt4gaKlAQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_meVt41ZIEfG1Qvt4gaKlAQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_meVt5FZIEfG1Qvt4gaKlAQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RfjKU1ZJEfG1Qvt4gaKlAQ" type="4001" element="_RfjKUFZJEfG1Qvt4gaKlAQ" source="_w-BY01ZIEfG1Qvt4gaKlAQ" target="_RfijQFZJEfG1Qvt4gaKlAQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RfjKVlZJEfG1Qvt4gaKlAQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RfjKV1ZJEfG1Qvt4gaKlAQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RfjKVFZJEfG1Qvt4gaKlAQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RfjKVVZJEfG1Qvt4gaKlAQ" points="[0, -21, -183, 114]$[0, -136, -183, -1]$[123, -136, -60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KWrYQ1ZLEfG1Qvt4gaKlAQ" type="4001" element="_KWrYQFZLEfG1Qvt4gaKlAQ" source="_w-BY01ZIEfG1Qvt4gaKlAQ" target="_KWqxOFZLEfG1Qvt4gaKlAQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KWrYRlZLEfG1Qvt4gaKlAQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KWrYR1ZLEfG1Qvt4gaKlAQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KWrYRFZLEfG1Qvt4gaKlAQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KWrYRVZLEfG1Qvt4gaKlAQ" points="[0, 22, -173, -83]$[0, 99, -173, -6]$[123, 99, -50, -6]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Lfpyg1ZLEfG1Qvt4gaKlAQ" type="4001" element="_LfpygFZLEfG1Qvt4gaKlAQ" source="_RfijQFZJEfG1Qvt4gaKlAQ" target="_LfpLcFZLEfG1Qvt4gaKlAQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LfpyhlZLEfG1Qvt4gaKlAQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Lfpyh1ZLEfG1Qvt4gaKlAQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LfpyhFZLEfG1Qvt4gaKlAQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LfpyhVZLEfG1Qvt4gaKlAQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ML9e41ZLEfG1Qvt4gaKlAQ" type="4001" element="_ML9e4FZLEfG1Qvt4gaKlAQ" source="_KWqxOFZLEfG1Qvt4gaKlAQ" target="_ML831FZLEfG1Qvt4gaKlAQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ML9e5lZLEfG1Qvt4gaKlAQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ML9e51ZLEfG1Qvt4gaKlAQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ML9e5FZLEfG1Qvt4gaKlAQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ML9e5VZLEfG1Qvt4gaKlAQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
